### ISSUE TITLE
when load Llama, AutoConfig will occur error.

### ISSUE THREAD

**Issue by kkkkk-ux** [Vahe1994/AQLM#92] opened 2024-05-23 08:44 UTC
when load Llama, AutoConfig will occur error, but LlamaForCausalLM can successfully load. Is this my environment error or other questions?

error line:    AQLM/src/modelUtils.py:50
if dtype == "auto":
        dtype = (
            AutoConfig.from_pretrained(model_path, trust_remote_code=trust_remote_code).torch_dtype or "auto"
        )  # force transformers 4.29.2 to follow the same rules as 4.30.x
    else:

**Comment by Vahe1994** [comment] 2024-05-30 11:44
Hello!
Can you please report error logs ?

**Comment by justheuristic** [comment] 2024-06-10 11:09
Closing this issue since there were no details for 2 weeks. Feel free to reopen if the issue re-occurs, but please add 1) full environment and 2) the error message with traceback. Ideally, please also try to reproduce this in some public cloud such as [google colab](https://colab.research.google.com/)

**Closed** 2024-06-10 11:10 UTC
